version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: amazon_optimizer_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: amazon_optimizer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

  backend:
    build: .
    container_name: amazon_optimizer_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "mysql://admin:admin123@mysql:3306/amazon_optimizer"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RAPIDAPI_KEY: ${RAPIDAPI_KEY}
      PORT: 5001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: